include("systems.jl")

println("### PIERWSZY TEST ###")
include("zal1.jl")
println("### DRUGI TEST ###")
include("zal2.jl")
println("### ZADANIE 4 ###")
include("lista5-zadanie4.jl")
println("### ZADANIE 5 ###")
include("lista5-zadanie5.jl")
println("### ZADANIE 6 ###")
include("lista5-zadanie6.jl")