wyrazenie([X|LISTA], WARTOSC, WYRAZENIE, 
	(
	LISTA \= [],
	(AKT =:= [],
	AKT2 = X; AKT =\= [], AKT2 = AKT),
	wyrazenie(LISTA, WARTOSC, WYRAZENIE2, AKT2 + X),
	WARTOSC =:= X + WYRAZENIE2,
	WYRAZENIE = X + WYRAZENIE2;
	wyrazenie(LISTA, WARTOSC, WYRAZENIE2, AKT2 - X),
	WARTOSC =:= X - WYRAZENIE2,
	WYRAZENIE = X - WYRAZENIE2;
	wyrazenie(LISTA, WARTOSC, WYRAZENIE2, AKT2 * X),
	WARTOSC =:= X * WYRAZENIE2,
	WYRAZENIE = X * WYRAZENIE2;
	wyrazenie(LISTA, WARTOSC, WYRAZENIE2, AKT2 / X),
	WARTOSC =:= X / WYRAZENIE2,
	WYRAZENIE = X / WYRAZENIE2
	);
	LISTA =:= [],
	WYRAZENIE = X.

